version: "2.4"

services:
  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    ports:
      - 8888:8888
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.7
    volumes:
      - ./influxdb:/tmp/influxdb/

  influxdb2:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    ports:
      - 9999:9999

  prometheus:
    image: prom/prometheus:v2.15.2
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/

  telegraf:
    image: telegraf:1.13
    volumes:
      - ./telegraf/:/etc/telegraf/
    depends_on:
      - influxdb
      - influxdb2
      - prometheus
