apiVersion: v1
kind: Service
metadata:
  name: {{ template "influxdb.fullname" . }}
  labels:
{{ include "influxdb.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "influxdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
