apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gitops
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        gitops.com/sha: fake_sha
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: gitops
spec:
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
