apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-nodes
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf-nodes
  template:
    metadata:
      labels:
        app: telegraf-nodes
    spec:
      serviceAccount: telegraf
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-nodes
      containers:
        - name: telegraf-nodes
          image: telegraf:master
          command:
            - telegraf
          imagePullPolicy: IfNotPresent
          resources: {}
          env:
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
