version: "2.4"

services:
  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    ports:
      - 8888:8888
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:1.7
    healthcheck:
      test: bash -c "</dev/tcp/localhost/8086"

  telegraf:
    image: telegraf:1.12
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/conf.d:/etc/telegraf/conf.d
    depends_on:
      influxdb:
        condition: service_healthy

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - ./jenkins/init.groovy.d:/usr/share/jenkins/ref/init.groovy.d/
